;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((org-mode . ((org-babel-load-languages . ((shell . t)
                                           (python . t)
                                           (lisp . t)
                                           (emacs-lisp . t)))
              (org-confirm-babel-evaluate . nil)
              (org-babel-python-command . "python3")
              (org-src-fontify-natively . t)
              (org-src-tab-acts-natively . t)
              (org-edit-src-content-indentation . 0)))
 (hy-mode . ((indent-tabs-mode . nil)
             (tab-width . 2)))
 (python-mode . ((python-shell-interpreter . "python3")
                 (python-shell-interpreter-args . "")))
 (makefile-mode . ((indent-tabs-mode . t)))
 (yaml-mode . ((indent-tabs-mode . nil)
               (yaml-indent-offset . 2))))